"""
Django settings for pjsautolit project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
from pathlib import Path

# ... other settings ...

BASE_DIR = Path(__file__).resolve().parent.parent
print(f"Base direct: {BASE_DIR}")
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pjsautolit', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ydu@0gbnw*q_q*+^k!&vn!%zcmz(d)%&+%l6&wcsh46!k5c()b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
]
EBAY_APP_ID = 'YASHWANT-pjauto-PRD-7c6937daa-890b1640'
EBAY_AUTH_TOKEN = "v^1.1#i^1#I^3#f^0#r^0#p^1#t^H4sIAAAAAAAAAOVYXWwUVRTudrsQAoUoCqYQWIc2InVm78z+zY7dld12YRfLdmVLaYsG7s7c2U47O7POnaVdMNBUrLEx+BNFAjECMfgAiRAfNMQfNCJJ0QABeYAYHzRKhGjEIEpUnJmWsq0EkG5iE/dlM+eee+73feece+8M6J00ZVF/rP9ypW1y+c5e0Ftus9FTwZRJjtrp9vIqRxkocrDt7K3ureizn6vDMCvnuBUI51QFI2dPVlYwZxmDRF5TOBViCXMKzCLM6TyXCi9v5BgKcDlN1VVelQlnvCFIIOiDflb0I5+H8bj9gmFVrsVsVoOEH7gFHwjwbhHQHkZ0G+MY51FcwTpU9CDBAMZDApYEvmbg57yAA27K76fbCWcL0rCkKoYLBYiQBZez5mpFWG8OFWKMNN0IQoTi4SWppnC8IZpornMVxQoN65DSoZ7Ho5/qVQE5W6CcRzdfBlveXCrP8whjwhUaWmF0UC58DcwdwLekZniWodMsK9CQYf18SZRcompZqN8chmmRBFK0XDmk6JJeuJWghhjpTsTrw08JI0S8wWn+PZaHsiRKSAsS0Ui4LZxMEqEEkrGqxBCZXJYK53W1kUyuaCDTwMsAj8gCkjEKyy/44PBCQ9GGVR6zUr2qCJKpGXYmVD2CDNRorDaeIm0MpyalSQuLuomo2C9wTUNPoN3M6VAS83qHYqYVZQ0hnNbjrTMwMlvXNSmd19FIhLEDlkRBAuZykkCMHbRKcbh6enCQ6ND1HOdydXd3U91uStUyLgYA2tW6vDHFd6AsJExfs9ctf+nWE0jJosIjYyaWOL2QM7D0GKVqAFAyRMgLjISAYd1HwwqNtf7DUMTZNbohStUgLArQHg+gaejjIWRRKTokNFykLhMHSsMCmYVaF9JzMuQRyRt1ls8iTRI4t1dk3KyISMEXEElPQBTJtFfwkbSIEEAoneYD7P+pUW631FOI15BemlovVZ3L6zqWdoh0Zv1S6I4+mWrNRpa55RZF6uzJLI+0BtLhTNaTicvhdFs0eLvdcEPy9bJkKNNsrF8SAcxeL5kIMRXrSBgXvRSv5lBSlSW+MLES7NaEJNT0QgrJsmEYF8lwLhcv0V5dKnr/cpu4M94lPKP+m/PphqywWbITi5U5HxsBYE6izBOI4tWsSzV7HRrXD9O8xkI9Lt6ScXGdUKwNkkNsJWHoykmpJl0Kr+MpDWE1rxmXbarJvIE1q11IMc4zXVNlGWkt9Lj7OZvN6zAto4nW2CUocAlOsMOW9jNMwA18wD0uXrx1lK6ZaFtSSbbiiiV3dq12jX7HD5VZP7rP9gnos31YbrOBOlBDLwD3T7KvrLBPq8KSjigJihSWMorx6qohqgsVclDSymeWXdz9aqy+Ktq0ddGG5sLxHUfKphV9Ytj5BLhv5CPDFDs9teiLA5h7fcRBz5hdyXgAa+Tb7wXA3Q4WXB+toGdV3HPY+cOOp58/H5zz0eLtC9lPHz60mW0FlSNONpujrKLPVpZ0sUdfvxLaP2/Oln0vP7vgwhugZlP1uf6BPxNnft31cQyvnSfM7q+M2iObH5nfdgosrt4/I8o+uvpLcu/gqaW1vlWHq6te/LFv0aGv637qOtuW2J1Zdeyt0w89+MofWaV2766I49LFWTXrtx6Nqj/vyXW+t94nKldwz4zA4Hd7D8w5GXNM92zb9+a7v5SvXPz59AK78krXvZNnXyIdoY0bBs+2fft9IjH/tN915q4LM2MpV8/agQ/qtnSsdm1sPPBM+4lK+qXOr965eqKz/fLcZVfZFeQ39oXnToK+B054zx/ZfnDLHuXty+8/fjcV+P2FvzbNnHa1NlLz1Nbjx1b99tpnqS8ODtZEtj23Z6AwlMu/AZtVXhH8EQAA"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pjsautolit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pjsautolit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
