# Generated by Django 5.0.7 on 2024-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('view_item_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('seller_username', models.CharField(max_length=255)),
                ('shipping_info', models.JSONField()),
                ('selling_status', models.JSONField()),
                ('listing_info', models.JSONField()),
                ('returns_accepted', models.BooleanField()),
                ('is_multi_variation_listing', models.BooleanField()),
                ('top_rated_listing', models.BooleanField()),
            ],
        ),
    ]
