# Generated by Django 5.0.7 on 2024-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_multi_variation_listing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='listing_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='returns_accepted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_username',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_rated_listing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_item_url',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
