name: Django CI/CD on Amazon Linux 2023

on:
  push:
    branches:
      - main  # Replace with the branch that triggers the build and deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          
          # Navigate to the project directory
          cd Ebay-to-Web-Store

          # Pull the latest changes from the Git repository
          git pull

          # Build the Docker image
          
          docker build -t yashwanthsc/pjsauto:latest ./backend/pjsautolit

          # Check for a running container and remove it if exists
          if docker ps --format '{{.Names}}' | grep -q pjs; then
            docker stop pjs
            docker rm pjs
          fi

          # Run the recently built Docker container
          docker run -d --name pjs -p 8000:8000 yashwanthsc/pjsauto:latest
